### ISSUE TITLE
Made a flask version

### ISSUE THREAD

**Issue by alphardex** [sdushantha/sherlock#10]
demo: https://sherlock-flask.herokuapp.com/
source: https://github.com/alphardex/sherlock

**Comment by hoadlck** [comment]
I found a website that already does checking for user name availability: https://www.namecheckr.com/

**Comment by bradley-Amuj** [comment]
Both the link to the Source Code and the hosted application on Heroku are down 

> demo: https://sherlock-flask.herokuapp.com/ source: https://github.com/alphardex/sherlock

As at 2 June 2023 both of these links are down
