### ISSUE TITLE
Optional csv Result Output

### ISSUE THREAD

**Issue by hoadlck** [sdushantha/sherlock#30]
While the text output file is good to have, it only shows the sites that do have an account with the username. It would be useful to also have a list of the sites that still had an opening.

I think that it would be useful to have a csv output as well.  It could be optional, so the user would have to add a `--csv` switch before the file would be output.  Then the output would be available in LibreOffice or Excel for users to sort and organize as they wish.

I am thinking of the following columns:

- Username
The user name that is being queried.
- Social Network Name
For example, "Twitter", "GitHub", ...
- Social Network Main URL
For example, "https://twitter.com/" for Twitter
- Social Network User URL
This is the URL that Sherlock would be trying to check the existence of.  For example, "https://twitter.com/user123" for Twitter.
- Username Exists
Will be either "True" or "False".
- Request Response Data
I think that this would be useful for debug of the program. Especially for those sites where Sherlock depends on the response text (as opposed to an explicit HTTP response code).

**Comment by mpieters93** [comment]
Awesome, I was also thinking of such a feature! If you end up not having time or the interest to work on this enhancement, feel free to assign it to me. Also feel free to @ me to discuss ideas.

For the columns: next to the request response data, perhaps the HTTP response code would be interesting to have in there as well?

**Comment by hoadlck** [comment]
Yes, adding the HTTP response code would be nice as well.  I can do that.

Unfortunately, I ran into a snag including the entire response into the csv.  I was able to generate the csv file without any problem, but when opening the file in LibreOffice, I got an error message that the cell was too long.  After seeing that, I remember having problems like this in Excel too: they did not really think that anyone would want to store really long data in one cell.

I don't think that there is any good workaround.  The contents of the file is stored in the CSV, but the user would have to open the file up in a text editor before seeing the results. Is it worth it?

**Comment by aggiebill** [comment]
I created a version with CSV output, not the same schema you suggested.  There is a pull request.  #32

**Comment by mpieters93** [comment]
> I don't think that there is any good workaround. The contents of the file is stored in the CSV, but the user would have to open the file up in a text editor before seeing the results. Is it worth it?

I think it still is: Excel, for example, does still open the file when certain cells contain too much text, but just truncates the contents of said cell. When a user wants to see the full output, it can chose a different file viewer. Furthermore, exporting as CSV allows for further processing down the line (for example in a Python or batch script), which can also be quite neat depending on your needs.
