### ISSUE TITLE
Sherlock sometimes tells me "Not Found!", even if user exists

### ISSUE THREAD

**Issue by elias6** [sdushantha/sherlock#45]
I ran `python3 sherlock.py sdushantha`, and it told me "Not Found!" for all of the sites.

Here is the strange thing: if I delete all of the sites from the data.json file except GitHub, and run `python3 sherlock.py sdushantha`, it finds your GitHub account. But if I have both GitHub and Issuu in data.json, it does not find your GitHub account (nor does it find anything on Issuu).

I am using Python 3.7.0 on macOS 10.12.6.

**Comment by NikxDa** [comment]
Same problem here, +1.

**Comment by sdushantha** [comment]
Thank you for letting me know. I will have to take look at it. I tried `sdushantha` and it gave me Not Found for all of them. I also tried `user123` and that gave me only positive results, even though the username did not exist in some sites.

**Comment by hoadlck** [comment]
This is a symptom of #46.  It is fixed now on the main branch.
