### ISSUE TITLE
Does it works on Windows 10? (Color Code)

### ISSUE THREAD

**Issue by jcs090218** [sdushantha/sherlock#57]
Hi, I really like this awesome tool. I followed the installation on the README page and ran the exact same command `python sherlock.py user123`, it gives me the correct result yet not the correct color text rendered. Does it fully supports on Windows 10? or I did something wrong? Thank you!

### Environment Info ###
OS: `Windows 10 (64-bit)`
Python Version: `3.7.1`
Software: `Windows PowerShell`, `Command Prompt`

### Screenshot ###
![sherlock-ss](https://user-images.githubusercontent.com/8685505/50573258-b411b800-0e0b-11e9-8cea-b6c446808b13.png)

**Comment by hoadlck** [comment]
This is a duplicate of #5. 

I am using Sherlock in a Git Bash shell, and it looks fine.  But, the other shells look funky.  

The results are valid though: try using the `--csv` option and look at the resulting file.

**Comment by jcs090218** [comment]
Oh, cool. Since this is the duplicate issue, I guess I will close this issue. I was searching for keyword `Windows 10`. My bad! And thanks for the tip!
