### ISSUE TITLE
usernames with "."

### ISSUE THREAD

**Issue by plgrazon** [sdushantha/sherlock#9]
It breaks when I search for a username that has a dot/period

**Comment by sdushantha** [comment]
You are right, I tried a username with a period and I got some strange error when it tries AngleList. Its strange though, when I visit https://angel.co/siddharth.dushantha I get a user, but if I make Python do it, I get nothing.

```python
import requests

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0'
}

r = requests.get("https://angel.co/siddharth.dushantha")

r.status_code
# 404

r.text
# ''
```

**Comment by hldh214** [comment]
possible missing `headers=headers`?
```python
import requests

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0'
}

r = requests.get("https://angel.co/siddharth.dushantha", headers=headers)

print('Siddharth Sivaraman' in r.text)
# True
```

**Comment by sdushantha** [comment]
@hldh214 
Thank you! I did not see that.

**Comment by sdushantha** [comment]
fixed it :)

**Comment by hoadlck** [comment]
After this change, any site that has the "noPeriod" attribute set to "True" in the json incorrectly says that the user name is not supported.  Even if they do *not* have a period set in their user name.

The if statement needs to check if there could even be a problem before doing the continue.  I will submit another pull request...

**Comment by sugizo** [comment]
test on ubuntu with Python 3.6.7
`python3 sherlock.py username.123`

**return:**
- Facebook: Illegal Username Format For This Site!
- Wix: Error!
- Error Connecting: Crevado

**here is the complete list:**
[-] Facebook: Illegal Username Format For This Site!
[-] Blogger: Illegal Username Format For This Site!
[-] GitHub: Illegal Username Format For This Site!
[-] DeviantART: Illegal Username Format For This Site!
[-] Flipboard: Illegal Username Format For This Site!
[-] Kongregate: Illegal Username Format For This Site!
[-] LiveJournal: Illegal Username Format For This Site!
[-] Dribbble: Illegal Username Format For This Site!
[-] Newgrounds: Illegal Username Format For This Site!
[-] Contently: Illegal Username Format For This Site!
[-] Slack: Illegal Username Format For This Site!
[-] WordPress: Illegal Username Format For This Site!
[-] Error Connecting: Wix
[-] Wix: Error!
[-] Error Connecting: Crevado
[-] Crevado: Error!
[-] Error Connecting: Carbonmade
[-] Carbonmade: Error!
[-] Coroflot: Not Found!
[-] Error Connecting: Jimdo
[-] Jimdo: Error!
